CREATE TABLE Users(
UserID BIGINT PRIMARY KEY,
Email VARCHAR(102) NOT NULL,
Fname VARCHAR(102) NOT NULL,
Lname VARCHAR(102) NOT NULL,
Mobile_Num VARCHAR(102) NOT NULL,
Password VARCHAR(130) NOT NULL,
Salt VARCHAR(18) NOT NULL,
User_Role VARCHAR(50) NOT NULL,
);

CREATE TABLE CD(
Movie_Name VARCHAR(50) PRIMARY KEY NOT NULL,
Unit_Price FLOAT NOT NULL,
);


CREATE TABLE OrderT(
UserID BIGINT FOREIGN KEY REFERENCES Users(UserID) NOT NULL,
Movie_Name VARCHAR(50) NOT NULL,
Order_Quantity INT NOT NULL,
Order_Date DATETIME NOT NULL,
Total_Price FLOAT NOT NULL,
);


